export const metadata = { title: "Terms of Service — NutriSafe" };

export default function TermsPage() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p className="legal-updated">Last updated: August 2026</p>

      <p>
        These Terms of Service ("Terms") govern your use of NutriSafe (the "Service"), a food
        ingredient analysis and diet planning application. By creating an account or using the
        Service, you agree to these Terms. If you don't agree, please don't use the Service.
      </p>

      <h2>1. What NutriSafe is — and isn't</h2>
      <p>
        NutriSafe uses AI to analyze packaged food ingredients against the health profile you
        provide (medical conditions, allergies, and dietary preferences) and returns a
        personalized suitability verdict (Good Fit, Use Caution, or Not Recommended), along with
        AI-generated diet and workout plans and a general health chat assistant.
      </p>
      <p>
        <strong>NutriSafe is not a medical device, and it does not provide medical advice,
        diagnosis, or treatment.</strong> Its analysis is generated by an AI model reading
        ingredient text and your self-reported profile — it is not a laboratory test, and it can
        be wrong. Always read product labels yourself, and always consult a qualified doctor or
        registered dietitian before making significant changes to your diet, especially if you
        are managing a chronic condition, are pregnant, or are making decisions for a child. In a
        medical emergency, contact emergency services — do not rely on NutriSafe.
      </p>

      <h2>2. Your account</h2>
      <ul>
        <li>You must provide accurate information when creating an account, including an accurate health profile — the personalization NutriSafe provides is only as good as the information you give it.</li>
        <li>You're responsible for keeping your login credentials secure and for all activity under your account.</li>
        <li>You must be old enough to legally consent to use a service like this in your country. NutriSafe is not directed at children, and we don't knowingly collect data from children — see our <a href="/legal/privacy">Privacy Policy</a>.</li>
        <li>If you're managing NutriSafe on behalf of someone else (a child, a parent, a dependent), you're responsible for the accuracy of the profile information you enter for them.</li>
      </ul>

      <h2>3. Subscriptions, payments, and Premium</h2>
      <p>
        Some features (currently: AI-generated Diet &amp; Workout Plans) require a paid Premium
        upgrade. The current price and billing structure are shown on the{" "}
        <a href="/premium">Premium page</a> at the time of purchase — that page is the source of
        truth for current pricing, not this document. Payments are processed by Razorpay; we do
        not store your full payment card details ourselves. For what happens if you want your
        money back, see our <a href="/legal/refund-policy">Refund Policy</a>.
      </p>
      <p>
        We may change pricing or the billing model (for example, moving from a one-time payment to
        a subscription) for future purchases. If that happens, we'll update this page and the
        Premium page before the change takes effect, and it won't retroactively change what you
        already paid for.
      </p>

      <h2>4. Usage limits</h2>
      <p>
        To keep the Service sustainable, scanning, AI chat, and diet plan generation are subject
        to usage limits that differ for free and Premium accounts. Current limits, and why they
        exist, are documented in full in our <a href="/legal/fair-usage">Fair Usage Policy</a> —
        that page always reflects what's actually enforced in the app.
      </p>

      <h2>5. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service to generate, store, or share content that is illegal, harmful, or infringes someone else's rights.</li>
        <li>Attempt to circumvent usage limits, reverse-engineer the Service, or access it through automated means outside of normal use.</li>
        <li>Use another person's account without permission, or create accounts to evade a suspension.</li>
        <li>Upload images or text that don't belong to you or that you don't have the right to submit for analysis.</li>
      </ul>

      <h2>6. Content and intellectual property</h2>
      <p>
        You retain ownership of the profile information, images, and text you submit. By
        submitting them, you give us permission to process them (including sending them to our AI
        and data processing providers, listed in our <a href="/legal/privacy">Privacy Policy</a>)
        for the purpose of providing the Service to you. The NutriSafe name, logo, and the
        Service's design and software are owned by us and may not be copied or reused without
        permission.
      </p>

      <h2>7. Disclaimer of warranties</h2>
      <p>
        The Service is provided "as is." We do our best to keep AI-generated analysis accurate and
        useful, but we don't guarantee it will be error-free, uninterrupted, or fit for a
        particular purpose. Ingredient databases and formulations can be wrong or out of date; AI
        models can misread label text or produce an incorrect verdict. Use your own judgment
        alongside the Service, not instead of it.
      </p>

      <h2>8. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, NutriSafe and its operators are not liable for
        indirect, incidental, or consequential damages arising from your use of the Service,
        including any health outcome resulting from reliance on an AI-generated analysis. Nothing
        in these Terms limits liability that cannot legally be limited.
      </p>

      <h2>9. Termination</h2>
      <p>
        You can stop using the Service and request account deletion at any time (see our{" "}
        <a href="/legal/privacy">Privacy Policy</a> for how). We may suspend or terminate accounts
        that violate these Terms, including attempts to abuse usage limits or the Service's
        infrastructure.
      </p>

      <h2>10. Changes to these Terms</h2>
      <p>
        We may update these Terms as the Service evolves. Material changes will be reflected here
        with an updated "Last updated" date. Continuing to use the Service after a change means
        you accept the updated Terms.
      </p>

      <h2>11. Contact</h2>
      <p>
        Questions about these Terms? Reach us at{" "}
        <a href="mailto:support@nutrisafe.app">support@nutrisafe.app</a>{" "}
        (update this to your real support inbox before treating this page as final).
      </p>
    </>
  );
}
